class VolunteerProfilePageLocators(object):

    PROFILE_FIRST_NAME = '//input[@name = "first_name"]'
    PROFILE_LAST_NAME = '//input[@name = "last_name"]'
    PROFILE_EMAIL = '//input[@name = "email"]'
    PROFILE_ADDRESS = '//input[@name = "address"]'
    PROFILE_CITY = '//select[@name = "city"]'
    PROFILE_STATE = '//select[@name = "state"]'
    PROFILE_COUNTRY = '//select[@name = "country"]'
    PROFILE_PHONE = '//input[@name = "phone_number"]'
    SELECT_ORGANIZATION = '//select[@name = "organization_name"]'
    UNLISTED_ORGANIZATION = '//input[@name = "unlisted_organization"]'
    SELECT_NONE_ORGANIZATION = '//*[@id="select"]/option[1]'
    RESUME_FILE = '//input[@name = "resume_file"]'
    DOWNLOAD_RESUME = './/*[@id="collapseResumeFile"]/div/form/button'
    EDIT_PROFILE_TEXT = 'Edit Profile'
    INVALID_FORMAT_MESSAGE = '//fieldset[1]/div[14]//div[1]//p[1]//strong'
    SUBMIT_PATH = '//form[1]'
